# Generated by Django 3.2.6 on 2021-08-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='amount',
            new_name='balance',
        ),
    ]
